# Default values for cardano-node.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: toky03/cardano-node
  pullPolicy: IfNotPresent
  tag: "1.30.1-1"
producingNode: false
  

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false

service:
  type: NodePort
  port: 3001
  
network: testnet
nodetype: producingNode

persistentVolume:
  accessModes:
    - ReadWriteMany
  size: 8Gi
  storageClass: manual
  nodeClaimName: cardano-pv-claim


autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50

